#pragma once

typedef enum dab_etat_e {
   DAB_ETAT_FIRST,

   DAB_ETAT_AUCUN = DAB_ETAT_FIRST,
   DAB_ETAT_MAINTENANCE,
   DAB_ETAT_HORS_SERVICE,
   DAB_ETAT_EN_SERVICE,
   DAB_ETAT_LECTURE_CARTE,
   DAB_ETAT_SAISIE_CODE_1,
   DAB_ETAT_SAISIE_CODE_2,
   DAB_ETAT_SAISIE_CODE_3,
   DAB_ETAT_SAISIE_MONTANT,
   DAB_ETAT_RETRAIT_CARTE,
   DAB_ETAT_RETRAIT_BILLETS,
   DAB_ETAT_RETRAIT_CARTE_ILLISIBLE,

   DAB_ETAT_LAST

} dab_etat;
