/*
 * generated by Xtext 2.19.0
 */
package org.hpms.dab.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.hpms.dab.dsl.DALRuntimeModule
import org.hpms.dab.dsl.DALStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DALIdeSetup extends DALStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DALRuntimeModule, new DALIdeModule))
	}
	
}
