COMP_CPP = Banque
CPP_SRCS = src/hpms/sc/Banque.cpp src/hpms/sc/BanqueUI.cpp src/hpms/sc/Repository.cpp
DLL_DEPS = -L../dab-lib -linterfaces-cpp -lutil-cpp -ldabtypes-cpp
WIN_DEPS = -lws2_32

include ../component.mk
