COMP_CPP = util
WIN_DEPS = -lws2_32
CPP_SRCS =\
 src/io/ByteBuffer.cpp\
 src/io/Console.cpp\
 src/io/DatagramSocket.cpp\
 src/io/Selector.cpp\
 src/io/sockets.cpp\
 src/os/Event.cpp\
 src/os/Condition.cpp\
 src/os/Mutex.cpp\
 src/os/sleep.cpp\
 src/os/Thread.cpp\
 src/util/Args.cpp\
 src/util/Exceptions.cpp\
 src/util/Time.cpp\
 src/util/Timeout.cpp
 
include ../component.mk
