COMP_C   = dabtypes-c
SRCS     =\
 src-gen/hpms/dabtypes/Information.c\
 src-gen/hpms/dabtypes/Compte.c\
 src-gen/hpms/dabtypes/Carte.c\
 src-gen/hpms/dabtypes/Evenement.c\
 src-gen/hpms/dabtypes/Etat.c

include ../common.mk
