/*
 * generated by Xtext 2.19.0
 */
package org.hpms.dab.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DALRuntimeModule extends AbstractDALRuntimeModule {
}
