/*
 * generated by Xtext 2.19.0
 */
package org.hpms.dab.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DALStandaloneSetup extends DALStandaloneSetupGenerated {

	def static void doSetup() {
		new DALStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
